version: "3.9"

services:
  label_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: label_web
    ports:
      - "8013:8013"
    volumes:
      - /serverdata/appdata/prod/label/Label_Config:/appconfig
      - /serverdata/appdata/prod/label/label_plugins:/app/elements/Custom
    # If your app needs environment variables, you can either add them here
    # under `environment:` or use an env_file, for example:
    # env_file:
    #   - .env
